spring:
   datasource:
    url: jdbc:mysql://localhost:3306/yx_studio?serverTimezone=GMT%2b8&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml

